# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: "$(buildConfiguration) Build"

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  name: unit_tests
  enabled: true
  inputs:
    command: test
    projects: '**/*Tests.Unit/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Integration Tests
  name: integration_tests
  enabled: true
  inputs:
    command: test
    projects: '**/*Tests.Integration/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet publish --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish to $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  name: publish_build_artifacts
  enabled: true

- task: DotNetCoreCLI@2
  displayName: "Publish $(BuildConfiguration) to $(Build.ArtifactStagingDirectory)"
  name: Zip Build Artifacts
  enabled: true
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureRmWebAppDeployment@3
  inputs:
    azureSubscription: '98032fb1-3410-430c-be36-dd4bed72acef'
    WebAppName: 'TuneageWebAPI'
    Package: $(System.ArtifactsDirectory)/**/*.zip