# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: "$(buildConfiguration) Build"

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  name: unit_tests
  enabled: true
  inputs:
    command: test
    projects: '**/*Tests.Unit/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Integration Tests
  name: integration_tests
  enabled: true
  inputs:
    command: test
    projects: '**/*Tests.Integration/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet publish --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish to $(Build.ArtifactStagingDirectory)'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  name: publish_build_artifacts
  enabled: false

- task: DotNetCoreCLI@2
  displayName: "Zip $(BuildConfiguration) to $(Build.ArtifactStagingDirectory)"
  name: ZipBuildArtifacts
  enabled: true
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- script: ls $(Build.ArtifactStagingDirectory) 
  displayName: 'Directory of $(Build.ArtifactStagingDirectory)'

# Azure App Service Deploy /home/vsts/work/1/s/**/*.zip
#                          /home/vsts/work/1/a
# Update Azure App Services on Windows, Web App on Linux with built-in images or Docker containers, ASP.NET, .NET Core, PHP, Python or Node.js based Web applications, Function Apps on Windows or Linux with Docker Containers, Mobile Apps, API applications, Web Jobs using Web Deploy / Kudu REST APIs
- task: AzureRmWebAppDeployment@4
  enabled: true
  inputs:
    connectionType: AzureRM
    azureSubscription: Tuneage-dontnet-api
    appType: 'webApp' # Required when connectionType == AzureRM# Options: webApp, webAppLinux, webAppContainer, functionApp, functionAppLinux, functionAppContainer, apiApp, mobileApp
    webAppName: TuneageWebAPI
    packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip' # Required when connectionType == PublishProfile || WebAppKind == WebApp || WebAppKind == ApiApp || WebAppKind == FunctionApp || WebAppKind == MobileApp || WebAppKind == WebAppLinux || WebAppKind == FunctionAppLinux
    #runtimeStack: # Optional
    #webConfigParameters: # Optional
    #appSettings: # Optional
    #configurationSettings: # Optional
    #enableCustomDeployment: false # Optional
    #deploymentType: 'webDeploy' # Required when enableCustomDeployment == True# Options: webDeploy, zipDeploy, runFromZip
    #takeAppOfflineFlag: true # Optional
    #setParametersFile: # Optional
    #removeAdditionalFilesFlag: false # Optional
    #excludeFilesFromAppDataFlag: true # Optional
    #additionalArguments: '-retryAttempts:6 -retryInterval:10000' # Optional
    #renameFilesFlag: true # Optional
    #enableXmlTransform: # Optional
    #enableXmlVariableSubstitution: # Optional
    #jSONFiles: # Optional